version: '3'

services:
  database:
    container_name: observer_postgres_databse
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 
      POSTGRES_DB: 
      POSTGRES_PASSWORD: 
    volumes:
      - database-data:/var/lib/postgresql/data

  server:
    container_name: observer_server
    build: .
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    env_file:
      - .env
    links:
      - database
    depends_on:
      - database
    command: ["npm", "run", "start"]

volumes:
  database-data: {}